### ISSUE TITLE
 failed business validation nop. 4.2

### ISSUE THREAD

**Issue by jnistal** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#13]
I have tried in sandbox and live mode but in both it shows the following error: 

The requested action could not be performed, semantically incorrect, or failed business validation.

**Comment by RomanovM** [comment]
@jnistal  I just tested the plugin on our demo site, everything is working correctly.
So try to ask on [our forums](https://www.nopcommerce.com/boards), but describe the problem in more detail, where you encounter it during configuration or during checkout, specify steps to reproduce, show a full error log, etc. 
If the community confirms there is an error, we'll reopen this issue.
