### ISSUE TITLE
Updated plugin not pushed to the repo

### ISSUE THREAD

**Issue by hodasza** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#15]
The plugin was updated: April 01,2021
https://www.nopcommerce.com/en/paypal-smart-payment-buttons
But the code in the repo is way older.

**Comment by RomanovM** [comment]
Yep, this plugin [was in the core until 4.40.4](https://github.com/nopSolutions/nopCommerce/commit/8bdaeabfb857b990dc5e6b1a02744742f0d1e238), all updates were made there.

**Comment by hodasza** [comment]
https://www.nopcommerce.com/en/paypal-smart-payment-buttons
"The plugin is provided absolutely for free and includes source code. Find the project Github repository _here_."
_here_ refers to this repo

If it _was_ in the core does that mean the support ends here?

**Comment by RomanovM** [comment]
Yes, now use PayPal Commerce instead.
