### ISSUE TITLE
Discount problem CANNOT_BE_NEGATIVE

### ISSUE THREAD

**Issue by alessior81** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#16]
I have this error

System.AggregateException: One or more errors occurred. ({"name":"UNPROCESSABLE_ENTITY","details":[{"field":"/purchase_units/@reference_id=='XXXXXXXXXX'/amount/breakdown/discount/value","value":"-0.01","issue":"CANNOT_BE_NEGATIVE","description":"Must be greater than or equal to 0. If the currency supports decimals, only two decimal place precision is supported."}],"message":"The requested action could not be performed, semantically incorrect, or failed business validation.","debug_id":"XXXXXXXXXX","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-CANNOT_BE_NEGATIVE","rel":"information_link","method":"GET"}]})   ---> PayPalHttp.HttpException: {"name":"UNPROCESSABLE_ENTITY","details":[{"field":"/purchase_units/@reference_id=='XXXXXXXXXX'/amount/breakdown/discount/value","value":"-0.01","issue":"CANNOT_BE_NEGATIVE","description":"Must be greater than or equal to 0. If the currency supports decimals, only two decimal place precision is supported."}],"message":"The requested action could not be performed, semantically incorrect, or failed business validation.","debug_id":"XXXXXXXXXX","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-CANNOT_BE_NEGATIVE","rel":"information_link","method":"GET"}]}     at PayPalHttp.HttpClient.Execute[T](T req)     --- End of inner exception stack trace ---     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)     at Nop.Plugin.Payments.PayPalSmartPaymentButtons.Services.ServiceManager.HandleCheckoutRequest[TRequest,TResult](PayPalSmartPaymentButtonsSettings settings, TRequest request) in D:\Net\nopcommerce\src\Plugins\Nop.Plugin.Payments.PayPalSmartPaymentButtons\Services\ServiceManager.cs:line 178     at Nop.Plugin.Payments.PayPalSmartPaymentButtons.Services.ServiceManager.<>c__DisplayClass22_0.<CreateOrder>b__0() in D:\Net\nopcommerce\src\Plugins\Nop.Plugin.Payments.PayPalSmartPaymentButtons\Services\ServiceManager.cs:line 412     at Nop.Plugin.Payments.PayPalSmartPaymentButtons.Services.ServiceManager.HandleFunction[TResult](PayPalSmartPaymentButtonsSettings settings, Func`1 function) in D:\Net\nopcommerce\src\Plugins\Nop.Plugin.Payments.PayPalSmartPaymentButtons\Services\ServiceManager.cs:line 123

I correct the ServiceManager.cs line 395

**Comment by RomanovM** [comment]
I guess it's the same as https://github.com/nopSolutions/nopCommerce/issues/5517. This was fixed in "PayPal Commerce" plugin, which is now used instead of "PayPal Smart Payment Buttons"

**Comment by alessior81** [comment]
thanks, but for nop 4.3 ?
