### ISSUE TITLE
Adding + in phone number creates payment error

### ISSUE THREAD

**Issue by nddsoft** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#3]
Adding a "+" in the telephone number creates the following error:

Payments.PayPalSmartPaymentButtons error:
One or more errors occurred. ({"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"74f283c16286c","details":[{"field":"/payer/phone/phone_number/national_number","value":"+660202020202","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_PARAMETER_SYNTAX","rel":"information_link","encType":"application/json"}]})

**Comment by skoshelev** [comment]
See the API rules:
![Orders API - PayPal Developer](https://user-images.githubusercontent.com/16875599/77074688-40ed6500-6a02-11ea-9415-6dcfb7b6688d.jpg)

**Comment by skoshelev** [comment]
See [details](https://www.nopcommerce.com/boards/topic/74346/payment-method-paypalsmartpaymentbuttons/page/2#259512)

**Comment by DmitriyKulagin** [comment]
Closed with [commit](https://github.com/nopSolutions/nopCommerce/commit/ae741a9e11205a4fefc05fe786a8c47197efac15)
