### ISSUE TITLE
Does not support comma in price. e.g. 19,99

### ISSUE THREAD

**Issue by nddsoft** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#4]
Example, using French language with Euro prices, such as "9,99 Euro", the payment creates this error:

Payments.PayPalSmartPaymentButtons error:
One or more errors occurred. ({"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"e11a59a689ee3","details":[{"field":"/purchase_units/@reference_id=='d38cd1f7-324e-4a9d-9795-48e4d703a6ad'/amount/breakdown/item_total/value","value":"10,99","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."},{"field":"/purchase_units/@reference_id=='d38cd1f7-324e-4a9d-9795-48e4d703a6ad'/amount/breakdown/discount/value","value":"0,00","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."},{"field":"/purchase_units/@reference_id=='d38cd1f7-324e-4a9d-9795-48e4d703a6ad'/amount/breakdown/shipping/value","value":"9,98","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."},{"field":"/purchase_units/@reference_id=='d38cd1f7-324e-4a9d-9795-48e4d703a6ad'/amount/value","value":"20,97","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."},{"field":"/purchase_units/@reference_id=='d38cd1f7-324e-4a9d-9795-48e4d703a6ad'/amount/breakdown/tax_total/value","value":"0,00","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."},{"field":"/purchase_units/@reference_id=='d38cd1f7-324e-4a9d-9795-48e4d703a6ad'/items/0/unit_amount/value","value":"10,99","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"The value of a field does not conform to the expected format."}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_PARAMETER_SYNTAX","rel":"information_link","encType":"application/json"}]})

**Comment by RomanovM** [comment]
See also: https://github.com/nopSolutions/nopCommerce/issues/4275
and https://www.nopcommerce.com/boards/topic/75397/paypalsmartpaymentbuttons-error

**Comment by AndreiMaz** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/4545

**Comment by AndreiMaz** [comment]
See https://github.com/nopSolutions/nopCommerce/issues/4545 (as it became the "out of the box" plugin)

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce/commit/492f9f622e60e22e5da0786627041c83ecac05fc
