### ISSUE TITLE
Suggestion to add additional fee

### ISSUE THREAD

**Issue by groundzero2010** [nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce#9]
Would like to see the option to add additional fees for each payment type within the SmartButtons.
Different fee for each Paypal, Paypal Credit, Venmo, Credit Card.
Similar to the Standard Paypal payment method.
By static fee or fee percentage.

**Comment by RomanovM** [comment]
@groundzero2010 This is a requirement of PayPal not to add additional fee to this plugin. But you can customize it since it's an open source.
